#Generic information
Config:
  package-name: com.example.helloandroid



Models:
  #A model
  SimpleData:
    id:
      type: int
      generated: true
    string:
      type: String
      generated: true
      columnName: "BOB"
    millis:
      type: long
    date:
      type: Date
    even:
      type: boolean

  Counter:
    id:
      type: int
      generated: true
    value:
      type: int
    date:
      type: Date


